@startuml
title TPL Domain - LTPL (Lebenspende)

hide methods
hide stereotypes
skinparam shadowing false
skinparam classAttributeIconSize 0
left to right direction

class LivingDonationEpisode
class LivingDonationEpisodeOrgan
class LivingDonationDonor
class Episode
class Patient

LivingDonationEpisode "1" -- "0..*" LivingDonationEpisodeOrgan
LivingDonationEpisode "1" -- "0..*" LivingDonationDonor
Episode "1" <-- "0..*" LivingDonationEpisode : recipient episode >
Patient "1" <-- "0..*" LivingDonationDonor : donor patient >

@enduml
